# Generated by Django 4.2.9 on 2024-01-15 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatroom',
            old_name='title',
            new_name='titles',
        ),
    ]
